name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to HM-GPT issues! Thank you for contributing to this community. 🙂"
        pr-message: "Welcome to HM-GPT pull requests. Thanks for your interest in improving the community. 🙂"
